// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using ZetList.Data;

namespace ZetMigrations.Migrations
{
    [DbContext(typeof(ZetListDatabase))]
    [Migration("20180412141408_Documents_Info2")]
    partial class Documents_Info2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290");

            modelBuilder.Entity("ZetList.Models.Document", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FilePath");

                    b.Property<string>("Info");

                    b.Property<string>("Info2");

                    b.Property<string>("Name");

                    b.Property<string>("NameAndFilePath");

                    b.HasKey("ID");

                    b.ToTable("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
